### ISSUE TITLE
Rename events and functions to be more consistent

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/mob-coding#1]
**Tasks for this issue:**

  - [x] Rename `editorChange` or `changeScroll` and `changeCursor` for a consistent naming scheme!

  - [x] Rename `handleNewCursorData`, `handleNewScrollData`, `handleEditorChange`, as well as `handleChangeCursor`, `handleChangeScroll`, and `handleUserTyping` functions! They should be more symmetrical!
    - Maybe something like `handleLocal[EVENT]` for local user input and `handleServer[EVENT]` for receiving the related SocketIO events?

  - [x] Rename `loggedIn` event and `handleUserLogin` function to better match other names.

  - [x] Rename `createNewGist` function to match other names.

  - [x] Update changes in event list table and flowchart
