### ISSUE TITLE
Simplify client-side code for determining when to fork/edit Gist

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/mob-coding#3]
**Tasks for this issue:**

  - [x] Remove the `gistNewlyCreated` Boolean
  - [x] Simplify the condition for whether to fork or edit a Gist where `gistNewlyCreated` was being used
  - [x] Remove "Gist has been edited once?" condition from the flowchart!
