### ISSUE TITLE
Rewrite all promise chains with async/await

### ISSUE THREAD

**Issue by LearningNerd** [LearnTeachCode/mob-coding#7]
**Tasks for this issue:**

  - [x] Replace all Promise chains with async/await in both the server-side and client-side code.
  - [x] See if async/await can simplify the `forkAndEditGist` and `editGist` functions so that the former doesn't need to call the latter. (It would be much nicer to have a function for forking and another function for editing!)
  - [x] Rewrite API calls to be executed in parallel wherever possible. (Note: looks like this wasn't even necessary anywhere, because the API calls aren't very complex at all.)
